spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug

jwt:
  secret: dGhpc0lzTXlTZWNyZXRLZXlNYWRlQnlKdWh5dW5Tb24=
  token-validity-in-seconds: 3600

auth:
  jwt:
    access-cookie-key: jwt
    refresh-cookie-key: refresh-jwt

server:
  servlet:
    session:
      tracking-modes: cookie


cookie:
  loginCookieName: userId