spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug

jwt:
  secret: secretKey
  token-validity-in-seconds: 60*60 #만료시간?