spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug

auth:
  jwt:
    secret: dGhpc0lzTXlTZWNyZXRLZXlNYWRlQnlKdWh5dW5Tb24=
    access-token-validity-in-seconds: 3600
    refresh-token-validity-in-days: 14
    access-cookie-key: jwt
    refresh-cookie-key: refresh-jwt

server:
  servlet:
    session:
      tracking-modes: cookie

session:
  loginBySession: userIdentify

cookie:
  loginCookieName: userId